[[local|localrc]]

ADMIN_PASSWORD=Admin123!
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

HOST_IP=192.168.150.3

LOGFILE=/opt/stack/logs/stack.sh.log
LOGDAYS=7
RECLONE=yes
ENABLE_DEBUG_LOG_LEVEL=True

disable_service n-net
enable_service q-svc
enable_service q-agt
enable_service q-dhcp
enable_service q-l3
enable_service q-meta
enable_service horizon

Q_AGENT=openvswitch
Q_ML2_PLUGIN_MECHANISM_DRIVERS=openvswitch
Q_ML2_TENANT_NETWORK_TYPE=vxlan

DOWNLOAD_DEFAULT_IMAGES=False
